#!/bin/bash

# Check release version in Dockerfile and setup.py

VERSION=`python -c "import tomllib; print(tomllib.load(open('pyproject.toml', 'rb'))['project']['version'])"`

echo ${VERSION}

python -m build . --wheel
